### ISSUE TITLE
feature not documented

### ISSUE THREAD

**Issue by exenza** [sfsam/Itsycal#115]
just donated 5$ I was looking for something like this for YEARS!

The documentation on the website https://www.mowglii.com/itsycal/datetime.html is not covering a feature in the time for the seconds, however it's possible to display seconds.

I'm successfully using this time format:
E d MMM - H:mm:ss

Will be great to update the documentation accordingly.

**Comment by sfsam** [comment]
@exenza I'm glad you got seconds to work. The table on that page is just for the most common format specifiers. There is a link at the bottom of that page to the full spec which does include seconds.

I left seconds out on purpose because if I had included it, people would use it and then complain to me that Itsycal was using more CPU than they liked. Well, that's because it is updating the UI every second. It's not a problem on computers today, but people will complain to me anyway. 

I'm going to to leave the page as it is and enterprising people who read to the bottom and find the link to the full spec can figure out how to use seconds and all the other format specifiers.
