### ISSUE TITLE
Day of month space between characters

### ISSUE THREAD

**Issue by tomthurstan** [sfsam/Itsycal#122]
It looks like using the 'd' format generated day of month has an extra space in between the characters when compared to the native month. See same length line in image below (native on right).

![image](https://user-images.githubusercontent.com/25342712/52738790-573b1d00-2fc7-11e9-8340-a0173dc1d11b.png)

**Comment by sfsam** [comment]
This is by design. Itsycal's typeface uses monospaced digits. You can see this with the "1" of the "19:36" above as well.
The reason to use monospaced digits is because otherwise the clock display would subtly shift every minute (or every second if you display seconds). The system clock has a bunch of extra padding on each side and does custom drawing to avoid these shifts.

**Comment by tomthurstan** [comment]
Ah I see. That's interesting. Thanks for the explanation!

**Comment by macbugs** [comment]
Just for reference, this is a duplicate of https://github.com/sfsam/Itsycal/issues/52
