### ISSUE TITLE
Version 0.11.17 not on GitHub

### ISSUE THREAD

**Issue by Jendker** [sfsam/Itsycal#144]
Hello,

I don't see the commits to version 0.11.17 on GitHub, but I got notification for update.
I am not sure if it's not something malicous, could you confirm, that it fine? Thanks!

**Comment by Jendker** [comment]
It would be nice to have the source code again on GitHub to be able to make the adjustments. Currently in the version 0.12.0 the text has went a bit higher for some reason. It would be nice to check, correct it and send PR, what would push this beautiful project forward.

![Bildschirmfoto 2019-09-24 um 10 15 34](https://user-images.githubusercontent.com/14967831/65494125-84806f80-deb4-11e9-8017-97dd1e5d45c3.png)

**Comment by sfsam** [comment]
I've been slow to update Github because someone has taken all the code for Itsycal and put it on the App Store as their own work. So far, working with Apple on this has gone nowhere for over a month. It has temporarily soured my enthusiasm for sharing. That said, I will likely update the code again. I'm just not quite ready yet.

Could you please create a new issue for the menubar bug? I will address it there.

**Comment by Jendker** [comment]
That sucks, I hope you will be able to straighten the things up soon!

I have created an issue which corresponds to the mentioned bug. Thanks a lot, closing this issue.
