### ISSUE TITLE
Doesn't use system accent color anymore

### ISSUE THREAD

**Issue by akaralar** [sfsam/Itsycal#148]
We can set accent color in System Preferences -> General https://take.ms/XHA0f

Itsycal used to take that color into account, with the latest update it shows a blue accent color https://take.ms/rDihY

version: 0.12.1
OS: 10.14.6

**Comment by sfsam** [comment]
I changed it back to a fixed color. I got complaints from people with low vision that the contrast made it hard to see. Since I have no control over what people choose as an accent color, I can't control the contrast in Itsycal. So I changed it back to the way it was before. You can't satisfy everyone...

**Comment by akaralar** [comment]
@sfsam would it be possible to add that as an option in preferences? I quite liked the fact that the accent colors are the same as the system, since the theme reflects what the system provides with "light" and "dark"

**Comment by sfsam** [comment]
I'm reserving preferences for larger things. As it is, there are a lot of them and most people miss features that already exist because of this. I get lots of requests for idiosyncratic preferences. I don't enjoy saying no, but if I did them all the UI would be a mess. The Mac calendar app uses a standard red color to highlight today rather than using the accent color. Everyone is fine with this. Itsycal uses a standard blue. In this case, I'm prioritizing control over providing accessibility versus some minor aesthetic configuration. That said, anything and everything is subject to change in the future. :)

**Comment by akaralar** [comment]
Alright, your decision sounds fair to me since you are providing the app for free and I can only thank you for that. 

>Everyone is fine with this. 

I don't use the mac Calendar app, and even if I did, it is the same color with my accent color :p joking aside, Fantastical works with system accent colors and I find it way more aesthetically pleasing than the stock Calendar.app. It has a free trial, you can see it for yourself (if you're not already a user)

I have been using itsycal for a long time and I am very happy with everything it provides, so I won't be uninstalling it just because it doesn't respect the accent color setting. Also I don't understand why visually impaired users select an accent color that makes it hard for them to see things, doesn't make any sense to me but I don't know any of them so I can't ask this question to them, there probably is a reason why they are doing it. For me I think I'll stick with the version that supports system accent colors instead of upgrading as long as it doesn't break (I hope it doesn't with Catalina,🤞) 

Thank you for taking the time to answer my request, and also thanks for all the time you spend towards making itsycal great. If you're curious, I would also happily pay a one-time fee for your app. Even if you don't want to sell, you can put a "donate" button of some sorts for people like me who would happily buy you coffee 🙂

**Comment by akaralar** [comment]
I just saw there is a donate option but unfortunately neither PayPal nor Stripe is available in my region (Turkey). I'll be moving to Spain within a few months and will be able to use PayPal then.

**Comment by sfsam** [comment]
Thank you for the kind words. 🙏
