### ISSUE TITLE
Itsyscal does not remember position in toolbar in MacOS Sierra

### ISSUE THREAD

**Issue by pskowronek** [sfsam/Itsycal#29]
Is it just me, or Itsyscal does not remember its position in toolbar in MacOS Sierra after restart?

On MacOS Sierra it is possible to move the itsyscal icon around toolbar alright, but after system restart or itsyscal restart the icon appears as the last one (on the left side).

I have no other mac with Sierra to verify this behavior though. Despite having itsyscal I have also menumeters, google drive and some others.

**Comment by pskowronek** [comment]
I have fixed the issue on my forked Itsyscal, pull request: #30

**Comment by sfsam** [comment]
Thank you. This was bothering me too and I didn't know about the autosavename for NSStatusItem. I just updated Itsycal to version 0.10.15 and included your position fix. I didn't include the terminate-on-removal part because in my testing it caused problems with remembering the position. The commit with the fix is here: [cd14303](https://github.com/sfsam/Itsycal/commit/cd143030ba7547379df3666962531e2cee8c61a8)
