### ISSUE TITLE
itsycal running afoul of GPR

### ISSUE THREAD

**Issue by JohnDCCIU** [sfsam/Itsycal#32]
itsycal v0.10.16 in macOS 10.12.1 throws up a dialog about needing to run from /Applications and quits...but it's already in /Applications.  I did try to run it once from ~/Downloads, but then moved it and it still refuses to run.

Seems like GPR is interfering, but 0.10.16 is apparently Sierra-ready?

**Comment by sfsam** [comment]
It's a mystery. I've had a couple people report this. In one case, they had unzipped the download from the command line. Unzipping by double-clicking on the .zip file and then manually dragging to /Applications solved it for them. I have no idea why that worked but their method didn't. #27 

All I can suggest is unzipping by double-clicking and then dragging from ~/Downloads to /Applications in the Finder. But this is probably what you did already.

I'll keep investigating. Please let me know if you figure anything out. FWIW, the code that checks if Itsycal is in the command line is in AppDelegate.m: https://github.com/sfsam/Itsycal/blob/master/Itsycal/AppDelegate.m#L83

**Comment by JohnDCCIU** [comment]
Thanks for the quick reply!  I did unzip it by double-clicking it, but I did also try to run it from ~/Downloads once.  I don't know GPR that well, but I do know that if you distribute via a zip file, it tries to run the app in some kind of read-only mounted disk image...maybe that's somehow still active and interfering.  I'll try a reboot to get a fresh environment.

Have you considered distributing itsycal via a signed installer or DMG?  I know it's a pain, but it should avoid all this GPR nonsense.

**Comment by JohnDCCIU** [comment]
Just rebooted and tried the same copy of the app in /Applications but no go.  I then deleted that copy, unzipped another one, dragged it to /Applications, launched it and got the Gatekeeper dialog asking whether I wanted to open it, now all is working.

I wonder if the app somehow gets "contaminated" by trying to launch elsewhere, and once that's the case, then a new copy is required, dragging it to /Applications before trying to launch it the first time?

**Comment by sfsam** [comment]
I'm glad it's working now and thanks for documenting what you did. 

I really have no idea what is happening. It seems like the vast majority of people unzip and move to /Applications using the GUI and it's ok so I'm leaving it the way it is for now. I believe GPR requires manually dragging from the download location, but I'm not 100% sure. I explored the signed DMG route (you're right - it's a pain), but the main issue there is how many people are confused by DMGs. 

I think the real issue is Apple's implementation of GPR. Itsycal doesn't load non-bundle resources so it isn't even affected by the exploit GPR is designed to thwart. But all apps, including Itsycal, are subject to GPR's somewhat mysterious requirements just the same.
