### ISSUE TITLE
Modernize UI

### ISSUE THREAD

**Issue by solomon23** [sfsam/Itsycal#45]
This is exactly what I was looking for but found the UI a bit dated.  I've updated it for me locally, do you want a pull request for it ? 

1. uses a tad larger calendar box size which makes the tooltip wider
2. removed the tooltip arrow
3. removed the outline on the white version in the toolbar
4. removed most of the curved edges
5. removed the shadows on the current month
6. softened some colors
7. agenda font is bigger and gives more space behind it
8. turrned on smooth fonts as it makes it much sharper in the toolbar for me

![Updated UI](https://www.dropbox.com/s/96315dk6e1rwgk7/Screenshot%202017-01-18%2013.00.41.png?raw=1)

**Comment by Fastidious** [comment]
@solomon23 looks good. Any changes to make a dark theme for it? Also, the calendar little circle on the side of the appointments isn't centre aligned to the text, but leaning to the top--a bug?

**Comment by solomon23** [comment]
I don't really need a dark theme one, so I'm probably not going to spend time on that.  I moved the dot down if you're building my version you can sync it up:

![img](https://www.dropbox.com/s/6uqs7emccxnc26h/Screenshot%202017-01-19%2009.31.44.png?raw=1)

**Comment by gith-account** [comment]
Can we make it so that Itsycal perfectly mimics the system's time and date in the toolbar (i.e., same font and size) so that one could replace the original with Itsycal entirely? Day-O 2 (http://www.shauninman.com/archive/2016/10/20/day_o_2_mac_menu_bar_clock) does that pretty well, but Itsycal has the nicer calendar. I like your changes. Could you provide the code or a binary for Sierra? One suggestion: make the previous month/current date/next month selectors in the upper right corner of the calendar gray. In my opinion, they do not deserve the extra attention that the blue color provides.

**Comment by chrismaifinancialassetmanagement** [comment]
@gith-account I requested this enhancement 24 days ago tiger ---> [https://github.com/sfsam/Itsycal/issues/43](url)

**Comment by solomon23** [comment]
@gith-account https://github.com/solomon23/Itsycal

**Comment by gith-account** [comment]
@solomon23 Great! Thank you. Let me suggest some changes in ViewController.m:

_CGContextSetShouldSmoothFonts(ctx, **false**) // was 'true'_

_NSOffsetRect(rect, 0, **2.0**) // was 1.5_

_monospacedDigitSystemFontOfSize:**14.0** // was 13.5_

It looks more like the original clock in MacOS Sierra with these changes. Only two things still need to be improved (see attachment):

1. The font is a little less condensed than in the original clock
2. The date in Itsycal is a comma separated list

I do not know how to easily change either of the two. Anyone?

You should revert your changes regarding the clock. Remove

_[template appendFormat:@" h:mm a"];_

and uncomment

_//    if (_clockFormat) {
//        [_iconDateFormatter setDateFormat:_clockFormat];
//        _statusItem.button.title = [_iconDateFormatter stringFromDate:[NSDate new]];
        [self updateClock];
//    }_

Hardcoding the clock format is not a good idea. You can easily change the format with

_defaults write com.mowglii.ItsycalApp ClockFormat "HH:mm"_

as described in https://github.com/sfsam/Itsycal/issues/25.

@sfsam What is your opinion on solomon23's modifications? I think they are an improvement and should be pulled. Your clock code works well. A "show clock in icon" option in the preferences may be a good idea now.

![2017-01-22-comparison](https://cloud.githubusercontent.com/assets/22495200/22182917/6282a456-e0b1-11e6-815d-1040ab73a7ab.png)

**Comment by sfsam** [comment]
@gith-account @solomon23 @Fastidious @ChrisMaiNotABot  I have been working on a new version that has a bunch of changes including giving some more flexibility for the icon in Preferences. You can test it and let me know what you think.

https://s3.amazonaws.com/itsycal/Itsycal-2017-01-21.zip

If you try it, please make sure it's the only version of Itsycal running on your system and make sure it is running from /Applications.

**Comment by Fastidious** [comment]
@sfsam I like it. I have liked `Itsycal` for a while. It would nice to add a toggle, so that the date will show similar to @solomon23's fork (or like @gith-account shows it), newer interface, and, of course, a dark version will make it sublime.

Don't get me wrong, I would have paid for `Itsycal` as is, but that what I mention would make it irresistible.

**Comment by gith-account** [comment]
@sfsam The changes look good. Thanks a lot.

Maybe add a title like "Clock format" above the clock format input field so that the user immediately (i.e., without using the help button) understands what the field is for (if he does not get it from the default content).

If I am not mistaken, you did not alter the popup calendar. The (calendar design) modifications by solomon23 should thus not conflict with your latest changes and I suggest to pull them as I see them as an improvement.

I have added a few more changes to solomon23's fork (in addition to what I already mentioned in my last comment). I introduced a secret setting "SystemClock". With 

_defaults write com.mowglii.ItsycalApp SystemClock "true"_

the user can now choose a third style besides 'icon' and 'outlined icon'. If that third style is chosen, the date format will be:

_EEE d MMM_

I do not know if the original menu bar date/clock is always in this format or locale dependent. If the latter is the case, the code will have to be further adapted to take that into account.

For the SystemClock style I changed the date font from 'monospacedDigitSystemFont' to 'systemFont'. This mimics the system clock better.

The time you render a little differently from the date and you made the following comments there:

_// Use monospaced font in case user sets custom clock format.
// We modify the default font with a font descriptor instead
// of using +monospacedDigitSystemFontOfSize:weight: because
// we get slightly darker looking ':' characters this way._

I would like to use the non-monospaced 'systemFont' for the clock part, too, but haven't touched that for now. The clock part is thus still a little too wide if compared to the system clock.

I am not a programmer and haven't figured out how to use Github properly, yet, so I will just attach the files I changed to this comment (Modifications.zip).

As regards solomon23's modifications I suggest some additional changes (see attachments) to his design:

- add more space at the top and slightly realign the 'month year' title on the left and the three buttons on the right for more symmetry (any advice how to do this?)
- indent the days in the appointment list (any advice how to do this?)
- remove the three icons "pin", "calendar" and "settings"; instead add a right-click menu ( right-click on Itsycal in the menu bar) with all the options of the "settings" button plus an "Open and pin Itsycal"; close pinned calendar easily with left click on Itsycal in the menu bar; open calendar app if "month year" title in upper left corner is clicked

Removing the buttons may seem a little extreme, but how often do you really need to change the settings, for example? Does that warrant a permanent button which clutters the interface?

Great work! Awesome tool!

![2017-01-23-comparison-calendar-guides](https://cloud.githubusercontent.com/assets/22495200/22188672/c1039e66-e117-11e6-8e64-521ef8f9cebe.png)
![2017-01-23-comparison-calendar](https://cloud.githubusercontent.com/assets/22495200/22188671/c1032364-e117-11e6-8392-ddfc2bdc82e9.png)
[Modifications.zip](https://github.com/sfsam/Itsycal/files/722459/Modifications.zip)

**Comment by gith-account** [comment]
Further modification of solomon23's fork to change margins/indentation as suggested in my previous comment:

In MoCalendar.m:

`vcon(@"H:|-16-[_monthLabel]-4-[_btnPrev]-1.5-[_btnToday]-1.5-[_btnNext]-14-|", NSLayoutFormatAlignAllCenterY); // was 8-4-2-2-6;`

`vcon(@"V:|-6-[_monthLabel]-6-[_dowGrid][_dateGrid]-1-|", 0); // was (-3)-6-1`

In AgendaViewController.m:

`[self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|-16-[_textField]-4-|" options:0 metrics:nil views:@{@"_textField": _textField}]]; // was 4-4`

**Comment by Fastidious** [comment]
@gith-account wow, very, very nice! Not being a programmer myself, would love to see those changes incorporated on an usable executable. Willing to test it exhaustively as well.

**Comment by sfsam** [comment]
@Fastidious 
>  It would nice to add a toggle, so that the date will show similar to @solomon23's fork (or like @gith-account shows it)

Perhaps I am misunderstanding this comment, but you can do that with the test version I posted up-thread. Just use this datetime pattern: `E, d MMM h:mm` and check the 'Hide icon' option.

**Comment by sfsam** [comment]
@solomon23 @gith-account I appreciate the changes you've made and I'm glad people are able to customize the look of the app to their personal preferences. Open-source and Github are pretty cool.

I'm not looking to make major changes to the way the app looks at this time. I like the curved edges, higher contrast, buttons, overall layout, and size. I'll probably tweak this stuff over time, but I'm not planning on big changes all at once.

> I would like to use the non-monospaced 'systemFont' for the clock part, too, but haven't touched that for now. The clock part is thus still a little too wide if compared to the system clock.

Wow, good eye. The system clock is indeed not monospaced _except when it displays seconds_. I'll make this change.

**Comment by solomon23** [comment]
@sfsam  no problem ! I did it for myself and in the spirit of open source thought I'd let you know.  I appreciate all your work on this, like I said, it was exactly what I was looking for. Cheers.

**Comment by sfsam** [comment]
@solomon23 I think the way you presented your changes was very cool. Cheers.

**Comment by gith-account** [comment]
> I'm not looking to make major changes to the way the app looks at this time.

I showed Itsycal to two friends yesterday (who immediately liked and now use it) and both preferred solomon23's design over the current one (they noticed the difference after installing your version and having seen the other design on my computer), but in the end it is your work and you before anyone else should like how it looks.

Allow me one more comment on that topic. The way (active) elements are currently highlighted is pretty inconsistent.

- preferences and calendar button: blue when active
- pin button: 3D button effect + pin changes (pinned down)
- prev/current/next buttons: always highlighted in blue

If the pin button was not highlighted with a 3D button effect but turned blue upon activation it would be more in line with the preferences and calendar button. It would also be more logical to only highlight the prev/current/next buttons when they are actually pushed.

Having said that, it is super nice of you to freely share the code and allow users to learn from and modify it and to actively discuss things here. Thanks a lot for that and also to @solomon23 for sharing the modifications.

As regards the clock format input field in the new version, both of the above mentioned friends did not instantly realise that they can also enter date elements there (and then hide the icon to mimic the system clock), so it may be a good idea to explicitly point that out in a previously suggested input field title (e.g., "Date and/or clock format").

Cheers!

**Comment by Fastidious** [comment]
@solomon23, do you have a signed binary of your version I could get my hands on?

**Comment by solomon23** [comment]
@Fastidious Sorry, I'm not going to release/maintain a fork.

**Comment by gith-account** [comment]
@somolom23 I have forked your fork to add the following changes and make them available to others in a proper manner:

1. Removed 3D look from pin button (btnPinAlt.imageset) and added blue overlay to alternate images (affects pin button) (MoButton.m)

2. Increased top-margin and left indentation of "current month/year" (MoCalendar.m)

3. Increased indentation of date rows in agenda (AgendaViewController.m) 

4. Added hidden "SystemClock" option (Itsycal.h, Itsycal.m, ViewController.m); can be activated to mimic the system clock (i.e., no icon borders; sets date format to "EEE d MMM"):

`$ defaults write com.mowglii.ItsycalApp SystemClock "true"`

4. Reverted your changes to date/clock format (no hardcoding of clock format) (ViewController.m); clock format can be defined with:

`$ defaults write com.mowglii.ItsycalApp ClockFormat "HH:mm"`

5. Font smoothing in status icon deactivated if "SystemClock" is true (ViewController.m) to make it look like the system clock

I can send a pull request if you want. All changes regarding the hidden "SystemClock" option will be obsolete with the release of 0.11.1, though. So maybe it is better to wait for @sfsam to release the 0.11.1 sources.

As regards the idea of removing the options button in favor of a right-click status item menu: so far I can open the options menu with a Ctrl-click on the status item, but have problems with positioning it.

As regards the idea of removing the calendar button in favor of clicking on "monthLabel": I can turn monthLabel into a clickable text field through changes in MoCalendar.m and MoCalendar.h but the showCalendarApp function and some related code is in ViewController.m, which makes it non-trivial to me.

I may not look further into removing those buttons, but it was fun to try.

@Fastidious, be brave and build it yourself. ;-) It is really not that difficult.

**Comment by Fastidious** [comment]
@gith-account just built it, using it, I love it!

One thing I noted. If I set the time to show seconds (`ss`), the entire date/time will slightly shift, because the font used is not monospaced. Apple's default doesn't do it, I am assuming they compensate that, somehow.

**Comment by gith-account** [comment]
@Fastidious, yes, that also happens when the minutes switch. I guess one would have to assign a fixed status item width to the clock to fix that. As @sfsam made changes to the clock in 0.11.1 and any clock related changes in 0.11.0 will probably become obsolete, I will not look into that.

**Comment by sfsam** [comment]
@Fastidious @gith-account For what it is worth, I initially changed the datetime font to non-monospaced based on @gith-account 's observation, but then changed it back because of the way it makes the menu bar shift (you'll see this in the commit history when I upload the changes). However, the font inside the icon is now non-monospaced. Addressing this for the datetime part is more complicated than simply adding some padding and it's not something I'm going to pursue. Apple's clock adds a lot of padding and only supports a very limited set of customizations (12/24 hours, am/pm, month, day) whereas Itsycal supports an arbitrary datetime pattern of any length and complexity.

**Comment by gith-account** [comment]
> Apple's clock adds a lot of padding and only supports a very limited set of customizations (12/24 hours, am/pm, month, day) whereas Itsycal supports an arbitrary datetime pattern of any length and complexity.

@sfsam, I see this as two different modes:

1. icon style with great freedom regarding customization; easier to do with monospaced font
2. system clock style; main goal is to imitate the system clock; better with non-monospaced font; can have very limited customization options 

If the user chooses the system clock style one could limit his customization options to a very simple subset (12/24 hours, am/pm, month, day) of Itsycal's capabilites (just what the system clock offers) and then handle a few things differently (i.e., non-monospaced font and padding) without having to consider all the scenarios that come with broader customization options.

I agree that the icon style, which is Itsycal's original style after all, should not be compromised in favor of a system clock style. The people who like the icon style have no problem with the monospaced fonts and their user experience should not be deteriorated to make the app nicer for those preferring a system clock style.
