### ISSUE TITLE
3/28 when it's actually 2/28

### ISSUE THREAD

**Issue by mattwkelly** [sfsam/Itsycal#49]
I'm using the custom timestamp: "e/d  H:mm".

Today is 2/28, but it's showing as 3/28 (if I change 'e' to 'E' it also says it's march, not feb). Note that my OS is in Spanish, so I'm not sure if that's contributing to the issue.

![captura de pantalla 2017-02-28 a las 1 45 19 pm](https://cloud.githubusercontent.com/assets/174449/23435455/661fb9aa-fdbc-11e6-9bf5-4da3507465cc.png)

**Comment by sfsam** [comment]
@mattwkelly Are you using 'e' or 'E' to get the month? The e/E pattern is for the day of the week. So in English today is 3 or Tue (for Tuesday). In Spanish it is 3/mar (for martes).

If you want the month, try M/d instead of e/d. If you click on the (?) in the preferences panel, it will take you to a web page with a partial table of common patterns. At the bottom is a link to the complete table of patterns.

Please let me know if I've misunderstood.

**Comment by mattwkelly** [comment]
Oh man, fail on my part. Thanks for clarifying, clearly a Spanish noob here.
