### ISSUE TITLE
High Power Usage on 10.13 High Sierra 

### ISSUE THREAD

**Issue by jbrodley** [sfsam/Itsycal#59]
On the 10.13 Beta 1 and Beta 2 the itsycal application would appear in the high energy usage report in the battery menu and activity monitor.  I am currently running build 17A291j and the latest itsycal beta for 10.13 posted in the 10.13 compatibility thread.   (0.11.3).

When looking at the High Energy details in activity monitor, it says itsycal is using the discrete graphics card, and this is the cause of the high energy usage. The activity monitor does not indicate that high energy graphics cards are required.

**Comment by sfsam** [comment]
@jbrodley My computers only have integrated graphics so I cannot see this myself.

Did Itsycal use the discrete graphics card on previous versions of macOS?

Can you tell me about your setup? Which Mac do you have (model/year/graphics)? Do you have a second monitor attached?

**Comment by elsonwu** [comment]
Similar issue here, I'm using MacBook 12" 2017 with macOS High Sierra Beta 7 (17A360a), Itsycal use more power than before.

<img width="1060" alt="usage" src="https://user-images.githubusercontent.com/372937/30207474-36b824ac-94c2-11e7-9b02-919b8c58c35b.png">

<img width="372" alt="screen shot 2017-09-08 at 6 21 28 pm" src="https://user-images.githubusercontent.com/372937/30207573-93882006-94c2-11e7-9645-de90585a5a02.png">

<img width="351" alt="screen shot 2017-09-08 at 6 21 32 pm" src="https://user-images.githubusercontent.com/372937/30207575-9404daa6-94c2-11e7-9b1f-8f2bdadc8624.png">

**Comment by sfsam** [comment]
@jbrodley How do you access "High Energy details" to see that Itsycal is using the discrete graphics card?
@elsonwu Is your computer also using a discrete graphics card? For what it's worth, I also show an average energy impact of around 1.63 on my Sierra MacBook Air. What was the average reading for you before?

**Comment by elsonwu** [comment]
@sfsam I remember it's less than 1.0 on previous macOS Sierra 10.12.5

**Comment by jbrodley** [comment]
@sfsam High Energy details are located in the Activity Monitor, the third tab called "energy".
It had sort of gone away (or i just hadn't noticed it as much) and now is back with the latest High Sierra beta again.

**Comment by jbrodley** [comment]
Also, my average Energy Impact for Itsycal in Energy is a 4.17 when i checked today. Only Spotify, Outlook and Chrome were higher on my computer.

**Comment by shatteringlass** [comment]
I'm on a late-2013 rMBP with no discrete graphics, running 17A362a (High Sierra GM). For me Itsycal is the second most CPU time consuming process, just behind kernel_task (which is just idle CPU time I guess). I think this correlates with higher energy impact (Itsycal has 1.7 on average for me, while iTerm2 has 2.8 and Safari has 7.7).

**Comment by cecilyen** [comment]
Actually, on 10.2, Itsycal is using more energy than I expected.
The average energy impact as measured Apple's activity monitor is 1.73 as for now. I only showed the calendar few time for the past 8 hours. It is far higher than many programs. For example, Flycut only used 0.04 for the same period of time, which I used much often than Itsycal.

**Comment by khad** [comment]
Found this while Googling for the same issue. Just got a new MacBook Pro and I'm paying a lot more attention to energy usage than I did on my MacBook Air.

* MacBook Pro with Touch Bar (13-inch, 2017, 3.1 GHz Intel Core i5, 16 GB 2133 MHz LPDDR3)
* macOS High Sierra 10.13 (17A362a)
* I pretty much never use Itsycal except to click it and see the calendar. (I don't use it to create new events, for example.)
* I don't have an external monitor.
* I only have integrated graphics (Intel Iris Plus Graphics 650 1536 MB)

I guess I'll be switching to [Day-O](https://shauninman.com/archive/2016/10/20/day_o_2_mac_menu_bar_clock) for now to see if it's any bittern energy because I only really use the "show me a calendar" part of Itsycal and never use it to view my own events or create new ones.

Let me know if there is any additional information I can provide, though. I'd be happy to help get this resolved.

<img width="800" alt="screen shot 2017-09-29 at 2 50 01 pm" src="https://user-images.githubusercontent.com/758113/31037628-d0ca5c26-a526-11e7-8a8a-f8d47fcaf8d3.png">
<img width="260" alt="screen shot 2017-09-29 at 2 53 12 pm" src="https://user-images.githubusercontent.com/758113/31037629-d0d3e08e-a526-11e7-8730-f018468bb7b2.png">
<img width="239" alt="screen shot 2017-09-29 at 2 53 14 pm" src="https://user-images.githubusercontent.com/758113/31037630-d0d920f8-a526-11e7-9288-3c5e7f1e6242.png">

**Comment by sfsam** [comment]
I've redone the timer code (for the clock and dimming past events) and it seems to help on my machine. Could you give it a try? Please note that you need to keep it running for at least 12 hours to see an effect because Activity Monitor's Avg Energy Impact is calculated over time.

https://s3.amazonaws.com/itsycal/Itsycal-20170930.zip

**Comment by khad** [comment]
Downloaded. Will give it a go.

For my own reference: Day-O has an average energy usage on my machine of 0.7.

**Comment by woj-tek** [comment]
I've updated the itsycal yesterday to the linked one and energy impact went down from roughly 1.5 to 0.03 so I would say issue is fixed.

**Comment by sfsam** [comment]
Good to hear. Mine went from 1.63 to 0.06.

**Comment by khad** [comment]
Itsycal "Avg Energy Impact" is now down to 0.05 (though I did see the average get as "high" as 0.10 yesterday). That's from 1.66 before, so I'd definitely consider this solved.

Day-O is at about 0.04 (been running them simultaneously just to see), and for all the additional functionality Itsycal includes, I think it's clear which one I'll be sticking with.

@sfsam, I know others posted as early as June, but you had a fix a mere 2 days after I posted. So to me this feels like a super quick fix. It's much appreciated. Just sent a token of my appreciation via PayPal. :)

If anyone else feels so inclined: https://www.paypal.me/mowgliiapps (or find the link in Preferences > About).

Have a great rest of your week!

**Comment by sfsam** [comment]
Thank you, @khad.

**Comment by elsonwu** [comment]
Thanks @sfsam for your quick action, now it went from 1.66 to 0.06 !!!

**Comment by klonos** [comment]
I've never noticed this issue before, but just wanted to chime in and say that for me the average energy impact indicator is 0.02

**Comment by erikw** [comment]
For me itsycal takes up huge amounts of CPU, 80% spotted, and is often unresponsive or frozen in the menu bar. This happens after it has been running for a while. When freshly started it works fine.

Using itsycal `0.11.8` on macOS `10.13.2`.

**Comment by sfsam** [comment]
@erikw Can you describe the kinds of calendars you are connecting to (Google, Outlook, etc.)? Can you relate the high cpu behavior to anything?

**Comment by erikw** [comment]
@sfsam Hmm so I have 1 Exchange calendar towards Office 356, set up in system Preferences, and also a Google account with 12 calendars, also set up with system Preferences.

I will try to related the CPU usage to something, the only pattern I've seen so far is that it always works good when freshly started, but after running for a while the problems occurs (I almost never reboot my macbook, just suspend it over night).

**Comment by sfsam** [comment]
@erikw Could you try removing the Exchange calendar (from Calendar.app, not just unchecking in Itsycal) and see if that makes any difference? Another user today [reported](https://github.com/sfsam/Itsycal/issues/54#issuecomment-361374738) that the issue went away when he did this. I only have Google calendar so I can't test this myself.

**Comment by erikw** [comment]
@sfsam With Exchange, itsycal memory usage is often 500-700MB. When I turned of my Exchange calendar it uses no more than 30-40MB. The UI is also way more snappy and responsive. So I guess my problem is the same as in #54

**Comment by sfsam** [comment]
I think this is the same as issue #54 which I believe has been fixed. 🤞
